version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: ad204476/nginx:a1
    ports:
      - "80:80"

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    image: ad204476/tomcat:a1
    ports:
      - "8081:8081"
